### ISSUE TITLE
No Matching Function Found Error

### ISSUE THREAD

**Issue by alayGit** [gracicot/kangaru#105]
Hello,
I am having issues with an unexplained error

Here is the error:

: Severity	Code	Description	Project	File	Line	Suppression State
Error	C2783	'detail::service_type_helper<T,void>::type kgr::container::service(Args &&...)': could not deduce template argument for '__formal'	TestKangaru	C:\Users\andre\source\repos\TestKangaru\TestKangaru\main.cpp	5	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2672	'kgr::container::service': no matching overloaded function found	TestKangaru	C:\Users\andre\source\repos\TestKangaru\TestKangaru\main.cpp	5	

I am using Kangaru 4.2.4 with MSVC through Visual Studio.

I couldn't find non Make instructions, so I just referenced the headers directly and everything seems to work fine. I have created other services without issue in the real application, it is just the one below that is giving me grief. 

Here is a minimum reproducible example:

```
container.h
#pragma once
#include "kangaru\kangaru.hpp"
#include "SoundOptions.h"
#include "SoundProcessor.h"

namespace A {
	namespace B {
		namespace Container {
			class UnmanagedContainer {
			public:
				struct SoundOptionsService : kgr::single_service<A::B::C::D::SoundOptions> {};
				struct SoundProcessorService : kgr::single_service<A::B::C::SoundProcessor>, kgr::dependency<SoundOptionsService> {};
				static kgr::container* getContainer();
				static void destroy();
			private:
				static kgr::container* _container;
			};
		} 
	} 
} 

container.cpp

#include "Container.h"
kgr::container* A::B::Container::UnmanagedContainer::_container;

kgr::container* A::B::Container::UnmanagedContainer::getContainer() {
	if (!_container) {
		_container = new kgr::container();
		//Add additional services in real application with emplace
	}
	return _container;
}

void A::B::Container::UnmanagedContainer::destroy() {
	if (_container) {
		_container->clear();
		delete _container;
		_container = nullptr;
	}
}

soundOptions.h
#pragma once
namespace A {
	namespace B {
		namespace C {
			namespace D {
				class SoundOptions {
				public:
					int sampleRate;
					int sampleSize;
					int soundPollingFrequencyMs;
					int serverFeedSize;
					int restAudioTime;

					SoundOptions();
				};
			}
		} 
	}
} 
soundOptions.cpp
#include "SoundOptions.h"

A::B::C::D::SoundOptions::SoundOptions()
{
}
soundProcessor.h
#pragma once
#include "SoundOptions.h"
#include <vector>
namespace A {
	namespace B {
		namespace C {
			class SoundProcessor {
			public:
				SoundProcessor(A::B::C::D::SoundOptions& soundOptions);
			};
		}
	} 
} 

soundProcessor.cpp
#include "SoundProcessor.h"

A::B::C::SoundProcessor::SoundProcessor(A::B::C::D::SoundOptions& soundOptions)
{
}


main.cpp
#include "container.h"
void main(char* args)
{
//No error for this line
	&A::B::Container::UnmanagedContainer::getContainer()->service<A::B::Container::UnmanagedContainer::SoundOptionsService>(); 

//Error for this line
	&A::B::Container::UnmanagedContainer::getContainer()->service<A::B::Container::UnmanagedContainer::SoundProcessorService(); 
}
```

**Comment by gracicot** [comment]
Hello! First thanks for using kangaru :)

Problem like this usually means that the service you're trying to use is invalid. In your case, `SoundOptionsService` is valid, but `SoundProcessorService` is not. Hence the error. With the newest fixes on master branch, you can try `kgr::debug::service<A::B::Container::UnmanagedContainer::SoundProcessorService>()`
 and it should output an error, and shows ambiguous call when there are many.

In your case, it's because you sent no dependency for `SoundProcessorService`. You inherit from `kgr::dependency`, but in reality, it's a parameter for `kgr::single_sevice`.

So this line:
```cpp
struct SoundProcessorService : kgr::single_service<A::B::C::SoundProcessor>, kgr::dependency<SoundOptionsService> {};
```

It should be that instead:
```cpp
struct SoundProcessorService : kgr::single_service<A::B::C::SoundProcessor, kgr::dependency<SoundOptionsService>> {};
```

Notice the single inheritance, and `kgr::dependency` being sent.

Let me know if you need further help!

**Comment by alayGit** [comment]
Thanks for your help and your quick response. I need a new pair of glasses :)

I am really impressed with your library. It is helping with organise a complicated set of dependencies for my game engine.

It's the only one I know of which works with C++/CLI.
