### ISSUE TITLE
No such file or directory: kangaru/detail/config.hpp

### ISSUE THREAD

**Issue by danny-mhlv** [gracicot/kangaru#117]
Hi! I'm not so sure if we can call it a *bug*, more of a minor inconvenience, I guess.

**Describe the bug**
When doing a fresh install of kangaru using CMake, `config.hpp` stays in the `build/generated/...` directory. Because of that you get `No such file or directory` for files:
```
type_id.hpp
default_source.hpp
exception.hpp
```

**To Reproduce**
Steps and code to reproduce the behavior:
1) Follow the CMake guideline in README.md
2) Include kangaru
3) Try to build

**Expected behavior**
Being able to use kangaru right after exporting preferences without tweaking/moving files, as it's mentioned in README.md. By the way, when going the "install" route - `config.hpp` is copied to where it should sit.

**Desktop:**
 - OS: Linux
 - Compiler: GCC
 - Version: 11.3.0

**Additional context**
I add kangaru as a git-submodule to my project. But found it when writing Dockerfile for my project, application simply couldn't find `config.hpp`.

**Comment by danny-mhlv** [comment]
Yep! Tested as you did - all seems to work good. That's my bad, I've missed the
`target_link_libraries(... PRIVATE kangaru::kangaru)` accidentally.

I do add kangaru as a dependency to my project, set `_REVERSE_DESTRUCTION` manually, my CMakeLists.txt looks like this:
```cmake
set(KANGARU_REVERSE_DESTRUCTION ON CACHE BOOL "" FORCE)
add_subdirectory("thirdparty/kangaru")
add_dependencies(lithium kangaru)
target_link_libraries(${MAIN_TARGET_NAME}
        PRIVATE kangaru::kangaru)
```

Sorry for bothering with that.
Can I suggest adding this extra-step (`target_link_libraries(...)`) to the README.md? It may be useful for novice guys like me.

Thank you for the detailed answer on the issue!

**Comment by danny-mhlv** [comment]
Somehow missed it completely...
Thanks a lot!

**Comment by gracicot** [comment]
No problem! Always happy to help :)
