### ISSUE TITLE
Update minimum CMake version to address compatibility warning

### ISSUE THREAD

**Issue by WopsS** [gracicot/kangaru#120]
**Is your feature request related to a problem? Please describe.**
CMake is issuing a warning indicating that compatibility with versions older than 3.5 will be removed in a future release.
```
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.

Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```

**Describe the solution you'd like**
Update the project's minimum required CMake version to 3.5 to ensure compatibility with future releases and get rid of this annoying message.

**Describe alternatives you've considered**
Alternatively, consider bumping the minimum required CMake version to an even newer release.

**Additional context**
I took a look at the `CMakeLists.txt` and it seems like upgrading to CMake version 3.5 should be fine. I'd be happy to provide a pull request for this, but before I do, I would like to know your opinion on this and if there was a specific reason to go with 3.0 (e.g. some specific requirements).

**Comment by gracicot** [comment]
I wouldn't consider upgrading to CMake 3.5 a breaking change. If you can open a PR I would greatly appreciate!
