### ISSUE TITLE
Supplying an already constructed service via emplace

### ISSUE THREAD

**Issue by andreparodi** [gracicot/kangaru#57]
Hi,

I would like to use the container with services that are generated outside of the container by another system. I would like to avoid having to emplace every new container managed service that has a dependency on an externally managed service. Ideally I would like something that allows me to register into the container and already constructed service that can later be automaticlly injected. In spring this would be something like the registerSingleton method.

Is this something that is already possible? 

Thanks
Andre

**Comment by gracicot** [comment]
Yes you could do that. This would be a form of non-owning service definition. It would look like that:

```c++
struct MyExternService : kgr::single_service<MyExtern*>, kgr::supplied {
    // This construct function receive a reference of MyExtern from emplace,
    // And receive no injected parameters
    static auto construct(MyExtern& my_extern) -> kgr::inject_result<MyExtern*> {
        return kgr::inject(&my_extern);
    }

    // This service resolves itself as a reference
    MyExtern& forward() {
        return *instance();
    }
};
```

This make not a service of `MyExtern`, but of `MyExtern*`, and this is what the definition will contain: a pointer to an already existing instance.

In the code example above, I overrided `construct` and `forward`. This is because even though the service is a pointer, we resolve that service as a reference, and send a reference to `emplace`.

You may use the service like that:

```c++
kgr::container container;
MyExtern my_extern;

container.emplace<MyExternService>(my_extern);
MyExtern& my_extern2 = container.service<MyExternService>();

assert(&my_extern == &my_extern2); // passes
```

This would be greatly simplified if reference services were supported by default, but you can do something equivalent with a custom generic service.

**Comment by andreparodi** [comment]
:+1: 

I am not entierly sure what you meant with the last sentence. Are you suggesting there is a whay for me to build a generic service? 

Anyway the solution you give works for me. I think this is a useful feature to add especially for people that might want to adopt the CI container into an existing application.

thanks for the help
andre

**Comment by gracicot** [comment]
No problem, thanks for the feedback!

When I said generic service, it's generic in the way `kgr::single_service` is. You can implement the service as a template base class, and all other external service will simply inherit from it.

In you case, simply rename `MyExternService`

**Comment by gracicot** [comment]
Here's an example of that:

```c++
template<typename T>
struct ExternalService : kgr::single_service<T*>, kgr::supplied {
    static auto construct(T& instance) -> kgr::inject_result<T*> {
        return kgr::inject(&instance);
    }

    T& forward() {
        return *instance();
    }
};
```

Then, use that template service:

```c++
struct MyExternService1 : ExternalService<MyExtern1> {};
struct MyExternService2 : ExternalService<MyExtern2> {};
```

You can also use alias there instead of inheritance, but it will prevent you from creating multiple service definition of the same type.

**Comment by gracicot** [comment]
Since your problem seems solved, I'll close this issue. Please comment on this one if you still have problem with that, and don't hesitate to open another one.
