### ISSUE TITLE
Split kangaru.hpp

### ISSUE THREAD

**Issue by Denisss025** [gracicot/kangaru#7]
What do you think about splitting *kangaru.hpp* into several files? The file growed from 200+ lines of code to 400+ lines of code.

I believe this would improve readability of the code. This would allow to minimize the number of merge conflicts.

I think about using such structure:

* include/
 * detail/
     * InstanceHolder.hpp
     * CallbackHolder.hpp
     * util.hpp
 * kangaru.hpp
 
If single *hpp* file is a major feature of the library, we could create a script that converts all the *hpp* files into a single one.

**Comment by gracicot** [comment]
I was thinking the same thing. It would help the readability of the code by a huge factor. I will fix that soon

**Comment by gracicot** [comment]
I don't think this was major feature. It surely simplify the whole downloading and using process, but I think it worth separating the header a bit.

**Comment by gracicot** [comment]
The header is now separated. Thank you again for your time!
