### ISSUE TITLE
Retrieve services by constraints

### ISSUE THREAD

**Issue by maxime-jeanson** [gracicot/kangaru#72]
Retrieve specific service through constraints (predicates or named) About constraints, by defining a service, one could also define metadata alongside it
```c++
class Shape {
public:
  virtual const std::string &name() const = 0;
};

struct ShapeService : kgr::abstract_service<Shape> {
  const std::string &name(const Shape &s) const {
    return s.name();
  }
};
```
and then one could do
```c++
container.service<ShapeService>(kgr::constraints<ShapeService>([] (const ShapeService &service) { service.name() == "Square"; };
```
or by not defining constraints directly in the service
```c++
container.service<ShapeService>(kgr::constraints<ShapeService>([] (const Shape &service) { service.name() == "Square"; };
```
both technique would work, the first one having the ability to friend the Shape class and not exposing metadata as public api

[Discussion of September 25, 2018 9:06 AM](https://gitter.im/gracicot/kangaru?at=5baa32bcaedb375b9c441b38)

**Comment by gracicot** [comment]
Here is a draft of an api that would fits well with other features of kangaru:

```c++
// Let `Shape` be a class type and `ShapeService` an abstract service
struct SelectingShapeService : kgr::selected_service<MyAbstractService> {
    static bool select(Shape const& s) {
        return s.name() == "square";
    }
};
```
When asking the container for a `SelectingShapeService` it will pick the first `MyAbstractService` that `select` returns true.

That way, we could still use the service map for constrained service:
```c++
auto service_map(Shape const&, kgr::map_t<Square>) -> SelectingShapeService;

container.invoke<kgr::map<Square>>([](Shape& shape) {
    // Shape obtained through `SelectingShapeService`
});
```
Let me know if this design cause problems.

**Comment by maxime-jeanson** [comment]
This design is great.  Now does it allow one to have 
```c++
// Let `Shape` be a class type and `ShapeService` an abstract service

// Let `SelectingQuadShapeService` be a selector for quadrilateral shapes
struct SelectingQuadShapeService : kgr::selected_service<ShapeService> {
    static bool select(Shape const& s) {
        return s.vertex_count() == 4;
    }
};

// Let `SelectingTriangleShapeService` be a selector for triangle shapes
struct SelectingTriangleShapeService : kgr::selected_service<ShapeService> {
    static bool select(Shape const& s) {
        return s.vertex_count() == 3;
    }
};
```

Then is it possible to invoke using a specified selector?

```c++
// Specifying the kgr::map_t<Square> isn't the same as not specifying it?
// Also, do we have to specify `service_map` for every selector?
auto service_map(Shape const&, kgr::map_t<Square>) -> ???;
auto service_map(Shape const&, kgr::map_t<Triangle>) -> ???;

// Same, is it required to specify the preferred shape if the selector is 
// there for selecting the shape matching some criteria?
container.invoke<kgr::map<Square>>([](Shape& shape) {
    // Shape obtained through `???`
});
```

**Comment by gracicot** [comment]
The service map is optional. It is only used if you want to invoke using the container (resolve injection through function parameter types). My general advise would be to use advanced mapping only to "namespace" the service map, or if you have a complex project, to partition many kind of invoking. I would do my best to keep the map as simple as possible and simply map the abstract service:

```c++
auto service_map(Shape const&) -> ShapeService;
```

Of course with any general advises, this may not apply to particular cases.

Otherwise if you want to map many constrained service to the same parameter type, I would advise giving a descriptive name to the constraint (like triangle and quad, that was good), and a map name that reflect the intent of the caller. For example:

```c++
struct SimpleShape {};
struct ComplexShape {};

auto service_map(Shape const&)                           -> ShapeService;
auto service_map(Shape const&, kgr::map_t<SimpleShape>)  -> SelectingTriangleShapeService;
auto service_map(Shape const&, kgr::map_t<ComplexShape>) -> SelectingQuadShapeService;
```
Then when invoking, use the map that match the intent:
```c++
container.invoke<kgr::map<SimpleShape>>([](Shape& shape) { // SimpleShape map
    // Shape is a simple shape, maybe a triangle or something like that.
});

container.invoke([](Shape& shape) { // default map
    // shape is the last inserted Shape in the container.
});
```
Of course, each service can be specified manually too:

```c++
struct ShapeDisplay {
    Shape const& shape;
};

struct ShapeDisplayService : kgr::service<ShapeDisplay,
    kgr::dependency<SelectingTriangleShapeService>> {}; // specify triangles

Shape const& shape = container.service<SelectingQuadShapeService>(); // specify quads
```

**Comment by maxime-jeanson** [comment]
Also, would this allow one to retrieve a set of `Shape`, that is, all shape that matches the given predicate?

**Comment by gracicot** [comment]
This would allow to retrieve a shape matching that predicate for one particular service type.

**Comment by gracicot** [comment]
I'm moving this feature to the next version. The current one took enough time to finish. Note that the required building blocks are here since you can retrieve a range of implementers of a service with #81

**Comment by gracicot** [comment]
Since we have override service ranges from #81 and with the new `kgr::optional` (soon on master), we can implement the feature on the user side easily:

```cpp
template<typename T, typename F> // requires(kgr::detail::is_polymorphic<T>::value and std::invocable<F, kgr::service_type<T>>)
auto select(kgr::container& c, F predicate) -> kgr::optional<kgr::service_type<T>> {
    auto result = kgr::optional<kgr::service_type<T>>{};
    auto const range = c.service<kgr::override_service_range<T>>();

    for (auto&& service : range) {
        if (predicate(std::as_const(service))) {
            result.emplace(std::forward<decltype(service)>(service));
            break;
        }
    }

    return result;
}
```

Since the fix is so easy to do now, I'll consider it done.
