### ISSUE TITLE
Generate dependency graph visualization

### ISSUE THREAD

**Issue by Dragnalith** [gracicot/kangaru#78]
I would love to be able to extend kangaru to visualize the dependency graph of a container.

**Comment by gracicot** [comment]
The container retains very little information about services. It contains a pointer to a service definition and optionally, a pointer to a function returning the contained instance. We could traverse the dependency tree for a service type at compile time and output a graph, but the dynamic service tree in a container would require a lot of intrusive changes.

**Comment by gracicot** [comment]
I will close this issue as won't fix. This is not implementable in kangaru 4. With kangaru 5 it will be possible to implement it quite easily, but probably won't be a built-in feature.
