### ISSUE TITLE
thread safeness

### ISSUE THREAD

**Issue by GeneralLoddes** [gracicot/kangaru#86]
Hey,
greate work!
Have you considered for thread safeness so far?
Greetings!

**Comment by gracicot** [comment]
As of right now indeed, there is not thread safety implemented. Non-const method cannot be called concurrently.

However there is a way to get thread safety right now and it's to use a forked container. Assign a fork of your container to each thread and you have thread safety for these containers.

```c++
kgr::container container;

// add class1 into the container
container.emplace<Class1Service>();

std::thread{[fork=container.fork()] {
    // simply retrieve Class1 from `container`.
    // `fork` observe every service available in `container` at the point it was forked
    Calss1& c1 = fork.service<Class1Service>();
}}.detach();

std::thread{[fork=container.fork()] {
    // Since Class2 was not in `container` at the forking point,
    // the thread will create an instance for itself, not affecting others.
    Calss2& c2 = fork.service<Class2Service>();
}}.detach();
``` 

That will work for most cases.

---

If you want thread to share instances between themself and create them on the fly, maybe #41 has your answer. It will allow users to customize the underlying storage of the container. One could customize it with a thread safe storage.

Also, I might add a const container in the future. It could support concurrent reads.


Let me know if that respond to your needs. Have a good day!

**Comment by gracicot** [comment]
Hello, I just wanted to followup before closing this issue. Has your question been answered correctly? Is there another problem related to thread safeness you'd need clarification?

**Comment by GeneralLoddes** [comment]
Hey, thanks!
That answered my question =)

**Comment by gracicot** [comment]
No problem, thanks for opening the issue! In fact, I was about to make a change that would have break that property, thanks for reminding me of this.
