### ISSUE TITLE
kgr::debug::service doesn't detect an error when service doesn't inherit from kgr classes

### ISSUE THREAD

**Issue by selat** [gracicot/kangaru#88]
If you pass some random class (not related to dependency injection) to kgr::debug::service it doesn't report an error.

**To Reproduce**
```C++

struct RandomService {};

int main() {
  kgr::container container;
  kgr::debug::service<RandomService>();
  return 0;
}
```

**Expected behavior**
Error message with something like "Class doesn't inherit from kgr::service".

**Desktop**
 - OS: macOS
 - Compiler: clang-1001.0.46.4

**Comment by gracicot** [comment]
Thanks for reporting. Service errors are really hard to maintain right now as they are not tested continuously. I'll take a look at it soon.

**Comment by gracicot** [comment]
It should print the correct error message now, and there are tests to enforce this.
