### ISSUE TITLE
Visual Studio 2019, Whole Program Optimization bug

### ISSUE THREAD

**Issue by bittersweetshimmer** [gracicot/kangaru#96]
When using the "whole program optimization" flag (`/GL`), the second `service` call seems to return a reference to previously returned object. Obviously it can end up in a segfault.

**To Reproduce**
Compile this snippet with and without the `/GL` flag using msvc.
```c++
#include <iostream>
#include <kangaru/kangaru.hpp>

struct Foo {
    int value = 42;
};

struct Bar {
    int value = 7;
};

struct FooService : kgr::single_service<Foo> {};
struct BarService : kgr::single_service<Bar> {};

int main(int argc, char* argv[]) {
    auto container = kgr::container();
    std::cout << container.service<FooService>().value << std::endl;
    std::cout << container.service<BarService>().value << std::endl;

    return 0;
}
```

**Expected behavior**
Should print 42 and 7 on both builds, which it does so without `/GL`, prints 42 twice instead when `/GL` is used.

**Desktop:**
 - OS: Windows 10
 - Compiler: MSVC
 - Version: 19.25.28610.4

**Comment by gracicot** [comment]
Thanks for reporting. This either look like a codegen bug or a non-standard optimization.

Question: Is the `/Gw` switch is enabled for this to happen? I [use the identity of some global data](https://codereview.stackexchange.com/questions/209950/unique-compile-time-constexpr-type-id-without-rtti) to identify services.

**Comment by bittersweetshimmer** [comment]
It's not present in my command line options, just to be sure I tried explicitly enabling and disabling `/Gw`. Doesn't make any difference.

**Comment by gracicot** [comment]
Hi, I reported the problem here: [Global constants are being merged when using whole program optimisation even though they are ODR used](https://developercommunity.visualstudio.com/content/problem/988440/global-constants-are-being-merged-when-using-whole.html)

In the meantime, I simply made the type_id content non const and it stopped merging them. I'll release a bugfix version with the patch.

**Comment by gracicot** [comment]
I finally posted a fix in all branches. I'll close this issue and tag new bugfix versions soon.
