### ISSUE TITLE
Conan package unavailable

### ISSUE THREAD

**Issue by AGreat1** [gracicot/kangaru#98]
Hi!
**Describe the bug**
The conan package does not appear to be available to my conan client despite the listing [here](https://bintray.com/gracicot/kangaru/kangaru). It is worth noting that bintray's search didn't find it among the packages, only the repositories. When I open the repository, it lists the package. Kind of weird. 

**To Reproduce**
I've added the conan remote as indicated in the "Set me up" button. I wasn't using authentication though (assumed it was not necessary since this is an open source package - it works that way for other repositories, like bincrafters' conan repository). Then I called `conan search *kangaru*` and no such package was found.

**Expected behavior**
`conan search kangaru` should yield the package information and I should be able to install it as a dependency from bintray.

**Desktop (please complete the following information):**
 - OS: Windows
 - Compiler -
 - Version -

**Comment by gracicot** [comment]
I don't think the conan package ever worked. I tried to create one and I'm not sure I did it the right way. I'll search for fixing this, but contributions are welcome.

**Comment by AGreat1** [comment]
I've submitted an issue for you [here](https://github.com/conan-io/conan-center-index/issues/1807). Don't know when it will actually be done, but I don't think your project should take long, since it's header-only. I might get to it myself in a few days.

**Comment by gracicot** [comment]
Thank you very much. As I understand, I need some sort of a conan file, and ideally, I'll be able to update the package without too much delay. I'm quite busy these days but in parallel I'll try to find some time to tinker with conan.

**Comment by AGreat1** [comment]
![image](https://user-images.githubusercontent.com/6637079/84233394-8ba6e680-aaf2-11ea-9314-fbc1f7503fe4.png)
This was my first contribution to an open source project(s). kangaru is now up on conan center!
